// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jihvttywtmjvjldmxxgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppaHZ0dHl3dG1qdmpsZG14eGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTI4NDYsImV4cCI6MjA2ODA2ODg0Nn0.KhPDG4V5hmzoydqbHPmPLcnRlWmAWTo7QU0Lf9BrdPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});